class NumberArray {
    static from(s) {
        if (s) {
            return s.split(',').map(parseInt);
        } else {
            return [];
        }
    }

    static to(a) {
        return a.join(',');
    }
}

const routes = {
    'bookmarks-page': {
        path: '/bookmarks/',
        hash: [
            'S${highlightStoryID}',
            's${scrollToStoryID}',
        ],
        params: {
            scrollToStoryID: Number,
            highlightStoryID: Number,
        },
        load: (match) => {
            match.params.ui = {
                navigation: { section: 'bookmarks' }
            };
            match.params.key = `${match.path}${match.search}`;
            return import('pages/bookmarks-page' /* webpackChunkName: "page-bookmarks" */).then((module) => {
                match.params.module = module;
            });
        }
    },
    'news-page': {
        path: '/news/',
        query: {
            roles: '${roleIDs}',
            search: '${search}',
            date: '${date}',
        },
        hash: [
            'S${highlightStoryID}',
            's${scrollToStoryID}',
            'R${highlightReactionID}',
            'r${scrollToReactionID}',
        ],
        params: {
            roleIDs: NumberArray,
            search: String,
            date: String,
            scrollToStoryID: Number,
            highlightStoryID: Number,
            scrollToReactionID: Number,
            highlightReactionID: Number,
        },
        load: (match) => {
            let statistics = { type: 'daily-activities', public: 'guest' };
            match.params.ui = {
                calendar: { statistics },
                filter: {},
                search: { statistics },
                navigation: { section: 'news' }
            };
            match.params.key = `${match.path}${match.search}`;
            return import('pages/news-page' /* webpackChunkName: "page-news" */).then((module) => {
                match.params.module = module;
            });
        }
    },
    'notifications-page': {
        path: '/notifications/',
        query: {
            date: '${date}',
        },
        hash: [
            'N${highlightNotificationID}',
            'n${scrollToNotificationID}',
        ],
        params: {
            date: String,
            highlightNotificationID: Number,
            scrollToNotificationID: Number,
        },
        load: (match) => {
            let route = {};
            let statistics = { type: 'daily-notifications', user_id: 'current' };
            match.params.ui = {
                calendar: { statistics },
                navigation: { section: 'notifications' }
            };
            match.params.key = `${match.path}${match.search}`;
            return import('pages/notifications-page' /* webpackChunkName: "page-notifications" */).then((module) => {
                match.params.module = module;
            });
        }
    },
    'people-page': {
        path: '/people/',
        query: {
            roles: '${roleIDs}',
            search: '${search}',
            date: '${date}',
        },
        hash: [
            'u${scrollToUserID}',
        ],
        params: {
            roleIDs: NumberArray,
            search: String,
            date: String,
            scrollToUserID: Number,
        },
        load: (match) => {
            let statistics = { type: 'daily-activities' };
            // go back to full list
            match.params.ui = {
                calendar: { statistics },
                filter: {},
                search: { statistics },
                navigation: { section: 'people' }
            }
            match.params.key = `${match.path}${match.search}`;
            return import('pages/people-page' /* webpackChunkName: "page-people" */).then((module) => {
                match.params.module = module;
            });
        }
    },
    'person-page': {
        path: '/people/${selectedUserID}/',
        query: {
            search: '${search}',
            date: '${date}',
        },
        hash: [
            'S${highlightStoryID}',
            's${scrollToStoryID}',
            'R${highlightReactionID}',
            'r${scrollToReactionID}',
        ],
        params: {
            search: String,
            date: String,
            selectedUserID: Number,
            scrollToStoryID: Number,
            highlightStoryID: Number,
            scrollToReactionID: Number,
            highlightReactionID: Number,
        },
        load: (match) => {
            // include user ID in URLs generated by search and calendar bar
            let { selectedUserID } = match.params;
            let route = { selectedUserID };
            let statistics = { type: 'daily-activities', user_id: selectedUserID };
            match.params.ui = {
                calendar: { route, statistics },
                search: { route, statistics },
                navigation: { section: 'people' }
            };
            match.params.key = `${match.path}${match.search}`;
            return import('pages/people-page' /* webpackChunkName: "page-people" */).then((module) => {
                match.params.module = module;
            });
        }
    },
    'settings-page': {
        path: '/settings/',
        load: (match) => {
            match.params.ui = {
                navigation: { section: 'settings '},
            };
            match.params.key = match.path;
            return import('pages/settings-page' /* webpackChunkName: "page-settings" */).then((module) => {
                match.params.module = module;
            });
        }
    },
    'diagnostics-page': {
        path: '/diagnostics/',
        load: (match) => {
            match.params.ui = {
                navigation: { section: 'settings '},
            };
            match.params.key = match.path;
            return import('pages/diagnostics-page' /* webpackChunkName: "page-diagnostics" */).then((module) => {
                match.params.module = module;
            });
        }
    },
    'start-page': {
        path: '/',
        query: {
            ac: '${activationCode}',
            p: '${activationSchema}',
        },
        params: {
            activationCode: String,
            activationSchema: String,
        },
        load: (match) => {
            match.params.ui = {
                navigation: { top: false, bottom: false }
            };
            match.params.key = match.path;
            return import('pages/start-page' /* webpackChunkName: "page-start" */).then((module) => {
                match.params.module = module;
            });
        },
        signIn: true,
    },
    'cordova-page': {
        path: '/@cordova/',
        load: (match) => {
            match.params.ui = {
                navigation: { top: false, bottom: false }
            };
            match.params.key = match.path;
            return import('pages/cordova-page' /* webpackChunkName: "page-cordova" */).then((module) => {
                match.params.module = module;
            });
        },
        public: true,
    },
    'error-page': {
        path: '*',
        load: (match) => {
            match.params.key = match.path;
            return import('pages/error-page' /* webpackChunkName: "page-error" */).then((module) => {
                match.params.module = module;
            });
        },
    },
};

export {
    routes,
};
